### PR TITLE
mfem parallel

### PR DESCRIPTION
**Pull request by dreamer2368**
- `PyMFEM` parallel version is now available in docker containers.
- `PyMFEM` installation instruction is updated in `README.md`.
- `examples/prom/poisson_global_rom.py` now uses parallel mfem. Running `python3 poisson_global_rom.py -offline -f 1.0 -id 0` returns the following output, faster than previous serial version:
```
Elapsed time for assembling FOM: 1.094717e+00 second

Elapsed time for solving FOM: 2.105834e-01 second
```
ROM online result remains the same as expected:
```
Elapsed time for assembling ROM: 1.121513e+00 second

Elapsed time for solving ROM: 2.288818e-05 second
```

### CODE REVIEW

**Comment by chldkdtn** [comment]
Thank you for working on this, @dreamer2368 . In LC, I get the following error when trying "python3 setup.py install --with-parallel --user"

subprocess.CalledProcessError: Command '/usr/tce/bin/python3 setup.py build_ext --inplace --parallel 35' returned non-zero exit status 1.

In LC, I see that swig is located in /usr/bin/swig

**Comment by dreamer2368** [comment]
@chldkdtn , I'd need more information to troubleshoot. It'd be great if you can spot the beginning of the error and post the message here (or attach the entire log).

I couldn't copy and paste the log details that includes my path in LC, so I have sent the log detail to you through Microsoft team.

**Comment by dreamer2368** [comment]
> In LC, I see that swig is located in /usr/bin/swig

This is the default swig installed in LC, which is outdated. I was able to install after `pip install swig`. Make sure `which swig` locates it at your local binary directory. You can also check if `swig --version` is `4.1.1`.

**Comment by chldkdtn** [comment]
This works great, @dreamer2368 ! Very well done. Would you mind put some example command line options to run those two examples in the beginning of each file, i.e., wave_equation.py and poisson_global_rom.py.

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
I also noticed that some screen outputs are repeated as multiple cores are used, e.g., "Options used" in prom example and DMD iterations in dmd examples.

**Pull request merged**
